DOG_BREEDS = [
	"Affenpinscher",
	"Airedale terrier",
	"Akbash",
	"Akita",
	"Akita americano (American akita)",
	"Alano español",
	"Alapaha blue blood bulldog",
	"American Staffordshire terrier",
	"Antiguo perro de muestra danés (Gammel Dansk Hønsehund)",
	"Antiguo perro de pastor inglés (Old English sheepdog, Bobtail)",
	"Australian silky terrier",
	"Azawakh",
	"Basenji",
	"Basset artesiano de Normandía (Basset artésien normand)",
	"Basset azul de Gascuña (Basset bleu de Gascogne)",
	"Basset hound",
	"Basset leonado de Bretaña (Basset fauve de Bretagne)",
	"Beagle",
	"Beagle-Harrier",
	"Bedlington terrier",
	"Bichón boloñés (Bolognese, Boloñés)",
	"Bichón de pelo rizado (Bichon à poil frisé)",
	"Bichón habanero (Bichon Havanais, Habanero)",
	"Bichón maltés (Maltese, Maltés)",
	"Billy",
	"Boerboel",
	"Border terrier",
	"Boston Terrier",
	"Boxer (Deutscher Boxer, Boxer alemán)",
	"Boyero australiano (Australian cattle dog)",
	"Boyero de Appenzell (Appenzeller Sennenhund)",
	"Boyero de Entlebuch (Entlebucher Sennenhund, Entlebucher)",
	"Boyero de Flandes (Bouvier des Flandres, Vlaamse Koehond)",
	"Boyero de las Ardenas (Bouvier des Ardennes)",
	"Boyero de montaña bernés (Berner Sennenhund)",
	"Braco alemán de pelo cerdoso (Deutsch Stichelhaar)",
	"Braco alemán de pelo corto (Deutsch Kurzhaar)",
	"Braco alemán de pelo duro (Deutsch Drahthaar)",
	"Braco alemán de pelo largo (Deutsch Langhaar)",
	"Braco de Ariege (Braque de l'Ariège)",
	"Braco de Auvernia (Braque d'Auvergne)",
	"Braco de Bourbonnais (Braque du Bourbonnais)",
	"Braco de Weimar (Weimaraner)",
	"Braco eslovaco de pelo duro (Slovenský Hrubosrsty Stavac, Ohar)",
	"Braco francés tipo Gascuña de talla grande (Braque français type Gascogne, grande taille)",
	"Braco francés tipo Pirineos talla pequeña (Braque français type Pyrénées, petite taille)",
	"Braco húngaro de pelo corto (Rövidszörü Magyar Vizsla, Vizsla)",
	"Braco húngaro de pelo duro (Drotzörü Magyar Vizsla)",
	"Braco italiano (Bracco Italiano)",
	"Braco Saint-Germain (Braque Saint-Germain)",
	"Briquet grifón vendeano (Briquet griffon vendéen)",
	"Broholmer",
	"Buhund noruego (Norsk Buhund)",
	"Bull terrier",
	"Bulldog",
	"Bulldog americano",
	"Bulldog francés (Bouledogue français)",
	"Bullmastiff",
	"Cairn terrier",
	"Cane corso italiano (Perro corso italiano)",
	"Caniche",
	"Cavalier King Charles Spaniel",
	"Cazador de alces noruego gris (Norsk Elghund Grå)",
	"Cazador de alces noruego negro (Norsk Elghund Sort)",
	"Cazador de alces sueco (Jämthund)",
	"Chesapeake Bay Retriever (Cobrador de la bahía de Chesapeake)",
	"Chihuahua",
	"Chow chow",
	"Cimarrón uruguayo",
	"Cirneco dell'Etna",
	"Clumber spaniel",
	"Cobrador de Nueva Escocia (Nova Scotia Duck Tolling Retriever)",
	"Cocker spaniel americano (American Cocker Spaniel)",
	"Cocker spaniel inglés (English Cocker Spaniel)",
	"Collie barbudo (Bearded collie)",
	"Collie de la frontera (Border collie)",
	"Collie de pelo corto (Collie smooth)",
	"Collie de pelo largo (Collie rough)",
	"Coton de Tuléar",
	"Crestado chino (Chinese Crested Dog)",
	"Curly Coated Retriever (Cobrador de pelo rizado)",
	"Dachshund",
	"Dálmata (Dalmatinac)",
	"Dandie dinmont terrier",
	"Doberman",
	"Dogo argentino",
	"Dogo canario",
	"Dogo de Burdeos (Dogue de Bordeaux)",
	"Dogo del Tíbet (Do-Khyi)",
	"Dogo mallorquín (Ca de Bou)",
	"Doguillo (Pug, Carlino)",
	"Espinone (spinone italiano)",
	"Eurasier",
	"Fila brasilero (Fila Brasileiro)",
	"Fila de San Miguel (Cão Fila de São Miguel)",
	"Flat Coated Retriever (Cobrador de pelo liso)",
	"Fox terrier de pelo de alambre (Wire fox terrier)",
	"Fox terrier de pelo liso (Smooth fox terrier)",
	"Foxhound americano (American foxhound)",
	"Foxhound inglés (English foxhound)",
	"Galgo español",
	"Gascon saintongeois",
	"Golden Retriever (Cobrador dorado)",
	"Gonzcy Polski",
	"Gos d'Atura Catalá (perro de pastor catalán)",
	"Gran basset grifón vendeano (Grand Basset griffon vendéen)",
	"Gran boyero suizo (Grosser Schweizer Sennenhund)",
	"Gran danés (Deutsche Dogge, Dogo alemán)",
	"Gran grifón vendeano (Grand griffon vendéen)",
	"Gran munsterlander (Grosser Münsterländer)",
	"Gran sabueso anglo-francés blanco y naranja (Grand anglo-français blanc et orange)",
	"Gran sabueso anglo-francés blanco y negro (Grand anglo-français blanc et noir)",
	"Gran sabueso anglo-francés tricolor (Grand anglo-français tricolore)",
	"Gran sabueso azul de Gascuña (Grand bleu de Gascogne)",
	"Greyhound",
	"Grifón azul de Gascuña (Griffon bleu de Gascogne)",
	"Grifón belga (Griffon belge)",
	"Grifón de Bruselas (Griffon bruxellois)",
	"Grifón de muestra bohemio de pelo duro (Ceský Fousek)",
	"Grifón de muestra Korthals de pelo duro (Griffon d'arrêt à poil dur Korthals)",
	"Grifón del Nivernais (Griffon nivernais)",
	"Grifón leonado de Bretaña (Griffon fauve de Bretagne)",
	"Harrier",
	"Hokkaïdo",
	"Hovawart",
	"Husky siberiano (Siberian Husky)",
	"Irish Glen of Imaal Terrier",
	"Irish soft coated wheaten terrier",
	"Jack Russell terrier",
	"Kai",
	"Kangal (perro de pastor turco)",
	"Kelpie australiano (Australian kelpie)",
	"Kerry blue terrier",
	"King Charles spaniel",
	"Kishu",
	"Klee Kai de Alaska (mini husky)",
	"Komondor",
	"Kromfohrländer",
	"Kuvasz",
	"Labrador Retriever (Cobrador del labrador)",
	"Laika de Siberia occidental (Zapadno-Sibirskaïa Laïka)",
	"Laika de Siberia oriental (Vostotchno-Sibirskaïa Laïka)",
	"Laika ruso-europeo (Russko-Evropeïskaïa Laïka)",
	"Lakeland terrier",
	"Landseer",
	"Lebrel afgano (Afghan Hound, Afgano)",
	"Lebrel árabe (Sloughi)",
	"Lebrel escocés (Deerhound)",
	"Lebrel húngaro (Magyar Agar)",
	"Lebrel irlandés (Irish Wolfhound)",
	"Lebrel polonés (Chart Polski)",
	"Lebrel ruso para la caza (Russkaya Psovaya Borzaya, Barzoï)",
	"Leonberger",
	"Lhasa Apso",
	"Lundehund noruego (Norsk Lundehund)",
	"Malamute de Alaska (Alaskan malamute)",
	"Manchester terrier",
	"Mastiff",
	"Mastín del Alentejo (Rafeiro do Alentejo)",
	"Mastín del Pirineo",
	"Mastín español",
	"Mastín napolitano (Mastino napoletano)",
	"Mudi",
	"Norfolk terrier",
	"Norwich terrier",
	"Parson Russell terrier",
	"Pastor alemán (Deutscher Schäferhund)",
	"Pastor australiano (Australian shepherd)",
	"Pastor australiano stumpy tail (Australian stumpy tail cattle dog)",
	"Pastor belga (Chien de berger belge)",
	"Pastor Bergamasco (Cane da pastore Bergamasco, Bergamasco)",
	"Pastor blanco suizo (Berger Blanc Suisse)",
	"Pastor croata (Hrvatski Ovcar)",
	"Pastor de Anatolia (Coban Köpegi)",
	"Pastor de Asia Central (Sredneasiatskaïa Ovtcharka)",
	"Pastor de Beauce (Berger de Beauce, Beauceron)",
	"Pastor de Bosnia-Herzegovina y Croacia (Tornjak)",
	"Pastor de Brie (Berger de Brie, Briard)",
	"Pastor de Karst (Kraski Ovcar)",
	"Pastor de los Pirineos de cara rasa (Berger des Pyrénées à face rase)",
	"Pastor de los Pirineos de pelo largo (Berger des Pyrénées à poil long)",
	"Pastor de Picardía (Berger de Picardie, Berger Picard)",
	"Pastor de Rusia Meridional (Ioujnorousskaïa Ovtcharka)",
	"Pastor de Shetland (Shetland sheepdog, Sheltie)",
	"Pastor del Cáucaso (Kavkazskaïa Ovtcharka)",
	"Pastor finlandés de Laponia (Lapinporokoïra)",
	"Pastor holandés (Hollandse herdershond)",
	"Pastor islandés (Islenskur Fjárhundur)",
	"Pastor mallorquín (Ca de Bestiar)",
	"Pastor Maremmano-Abruzzese (Cane da pastore Maremmano-Abruzzese)",
	"Pastor polaco de las llanuras (Polski Owczarek Nizinny)",
	"Pastor polaco de Podhale (Polski Owczarek Podhalanski)",
	"Pastor portugués (Cão da Serra de Aires)",
	"Pastor rumano de los Cárpatos (Ciobanesc Romanesc Carpatin, Carpatin)",
	"Pastor rumano de Mioritza (Ciobanesc Romanesc Mioritic)",
	"Pekinés (Pekingese)",
	"Pequeño basset grifón vendeano (Petit Basset griffon vendéen)",
	"Pequeño brabanzón (Petit Brabançon)",
	"Pequeño lebrel italiano (Piccolo Levriero Italiano)",
	"Pequeño munsterlander (Kleiner Münsterländer)",
	"Pequeño perro holandés para la caza acuática (Kooikerhondje)",
	"Pequeño Perro León (Petit chien lion, Lowchen)",
	"Pequeño perro ruso (Russkiy Toy)",
	"Pequeño sabueso azul de Gascuña (Petit bleu de Gascogne)",
	"Perdiguero alemán (Deutscher Wachtelhund)",
	"Perdiguero de Burgos",
	"Perdiguero de Drente (Drentse Patrijshond)",
	"Perdiguero frisón (Stabyhoun)",
	"Perdiguero portugués (Perdigueiro Português)",
	"Perro de agua americano (American Water Spaniel)",
	"Perro de agua de Romagna (Lagotto Romagnolo)",
	"Perro de agua español",
	"Perro de agua francés (Barbet)",
	"Perro de agua frisón (Wetterhoun)",
	"Perro de agua irlandés (Irish Water Spaniel)",
	"Perro de agua portugués (Cão de agua Português)",
	"Perro de Canaán (Canaan Dog)",
	"Perro de Castro Laboreiro (Cão de Castro Laboreiro)",
	"Perro de Groenlandia (Grønlandshund)",
	"Perro de los faraones (Pharaoh hound)",
	"Perro de montaña de la Sierra de la Estrella (Cão da Serra da Estrela)",
	"Perro de montaña de los Pirineos (Chien de montagne des Pyrénées)",
	"Perro de montaña del Atlas (Chien de Montagne de l'Atlas, Aïdi)",
	"Perro de nutria (Otterhound)",
	"Perro de osos de Carelia (Karjalankarhukoira)",
	"Perro de Taiwán (Taiwan Dog)",
	"Perro finlandés de Laponia (Suomenlapinkoira)",
	"Perro jindo coreano (Korea Jindo Dog)",
	"Perro lobo checoslovaco (Ceskoslovenský Vlcak)",
	"Perro lobo de Saarloos (Saarlooswolfhond, Saarloos)",
	"Perro negro y fuego para la caza del mapache (Black and tan coonhound)",
	"Perro sin pelo del Perú",
	"Perro sin pelo mexicano (Xoloitzcuintle)",
	"Perro smous holandés (Hollandse Smoushond)",
	"Perro sueco de Laponia (Svensk Lapphund)",
	"Perro tailandés con una cresta sobre la espalda (Thai ridgeback dog)",
	"Perro tejonero alpino (Alpenländische Dachsbracke)",
	"Perro tejonero de Westfalia (Westfälische Dachsbracke)",
	"Perro tejonero sueco (Drever)",
	"Pinscher alemán (Deutscher Pinscher)",
	"Pinscher austriaco (Österreichischer pinscher)",
	"Pinscher miniatura (Zwergpinscher)",
	"Pitbull terrier americano",
	"Podenco canario",
	"Podenco ibicenco",
	"Podenco portugués (Podengo Português)",
	"Pointer inglés (English Pointer)",
	"Poitevin",
	"Porcelana (Porcelaine)",
	"Pudelpointer",
	"Puli",
	"Pumi",
	"Rastreador de las montañas de Baviera (Bayrischer Gebirgsschweisshund)",
	"Rastreador del Hanover (Hannover'scher Schweisshund)",
	"Rhodesian ridgeback (Perro crestado rodesiano)",
	"Rottweiler",
	"Sabueso alemán (Deutsche Bracke)",
	"Sabueso anglo-francés de tamaño mediano (Anglo-Français de petite vénerie)",
	"Sabueso artesiano (Chien d'Artois, Artois)",
	"Sabueso austriaco negro y fuego (Brandlbracke, Vieräugl)",
	"Sabueso de Bosnia de pelo cerdoso (Bosanski Ostrodlaki Gonic Barak, Barak)",
	"Sabueso de Halden (Haldenstøvare)",
	"Sabueso de Hamilton (Hamiltonstövare)",
	"Sabueso de Hygen (Hygenhund)",
	"Sabueso de Istria de pelo corto (Istarski Kratkodlaki Gonic)",
	"Sabueso de Istria de pelo duro (Istarski Ostrodlaki Gonic)",
	"Sabueso de montaña de Montenegro (Crnogorski Planinski Gonic)",
	"Sabueso de Posavaz (Posavski Gonic)",
	"Sabueso de San Huberto (Chien de Saint-Hubert, Bloodhound)",
	"Sabueso de Schiller (Schillerstövare)",
	"Sabueso de Smaland (Smålandsstövare)",
	"Sabueso de Transilvania (Erdélyi Kopó)",
	"Sabueso del Ariege (Ariégeois)",
	"Sabueso del Tirol (Tiroler Bracke)",
	"Sabueso eslovaco (Slovenský Kopov)",
	"Sabueso español",
	"Sabueso estirio de pelo áspero (Steirische Rauhhaarbracke)",
	"Sabueso finlandés (Suomenajokoira)",
	"Sabueso francés blanco y naranja (Français blanc et orange)",
	"Sabueso francés blanco y negro (Français blanc et noir)",
	"Sabueso francés tricolor (Français tricolore)",
	"Sabueso helénico (Hellinikos Ichnilatis)",
	"Sabueso italiano de pelo corto (Segugio italiano)",
	"Sabueso italiano de pelo duro (Segugio italiano)",
	"Sabueso noruego (Dunker)",
	"Sabueso polaco (Ogar Polski)",
	"Sabueso serbio (Srpski Gonic)",
	"Sabueso suizo (Schweizer Laufhund-Chien Courant Suisse)",
	"Sabueso suizo pequeño (Schweizerischer Niederlaufhund, Petit chien courant suisse)",
	"Sabueso tricolor serbio (Srpski Trobojni Gonic)",
	"Saluki",
	"Samoyedo (Samoiedskaïa Sabaka)",
	"San Bernardo (St. Bernhardshund, Bernhardiner)",
	"Sarplaninac",
	"Schapendoes neerlandés (Nederlandse schapendoes)",
	"Schipperke",
	"Schnauzer",
	"Schnauzer gigante (Riesenschnauzer)",
	"Schnauzer miniatura (Zwergschnauzer)",
	"Scottish terrier",
	"Sealyham terrier",
	"Setter Gordon (Gordon Setter)",
	"Setter inglés (English Setter)",
	"Setter irlandés rojo (Irish Red Setter)",
	"Setter irlandés rojo y blanco (Irish Red and White Setter)",
	"Shar pei",
	"Shiba",
	"Shih Tzu",
	"Shikoku",
	"Skye terrier",
	"Spaniel azul de Picardía (Epagneul bleu de Picardie)",
	"Spaniel bretón (Epagneul Breton)",
	"Spaniel continental enano (Epagneul nain Continental)",
	"Spaniel de campo (Field Spaniel)",
	"Spaniel de Pont-Audemer (Epagneul de Pont-Audemer)",
	"Spaniel francés (Epagneul français)",
	"Spaniel japonés (Chin)",
	"Spaniel picardo (Epagneul picard)",
	"Spaniel tibetano (Tibetan Spaniel)",
	"Spitz alemán (Deutscher Spitz)",
	"Spitz de los Visigodos (Västgötaspets, Vallhund sueco)",
	"Spitz de Norrbotten (Norrbottenspets)",
	"Spitz finlandés (Suomenpystykorva)",
	"Spitz japonés (Nihon Supittsu)",
	"Springer spaniel galés (Welsh Springer Spaniel)",
	"Springer spaniel inglés (English Springer Spaniel)",
	"Staffordshire bull terrier",
	"Sussex spaniel",
	"Tchuvatch eslovaco (Slovenský Cuvac)",
	"Terranova (Newfoundland)",
	"Terrier australiano (Australian terrier)",
	"Terrier brasileño (Terrier brasileiro)",
	"Terrier cazador alemán (Deutscher jagdterrier)",
	"Terrier checo (Ceský Teriér)",
	"Terrier de juguete inglés negro y fuego (English Toy Terrier)",
	"Terrier galés (Welsh terrier)",
	"Terrier irlandés (Irish terrier)",
	"Terrier japonés (Nihon teria)",
	"Terrier negro (Tchiorny terrier, Terrier negro ruso)",
	"Terrier tibetano (Tibetan Terrier)",
	"Tosa",
	"Volpino italiano",
	"Welsh Corgi Cardigan",
	"Welsh Corgi Pembroke",
	"West highland white terrier",
	"Whippet",
	"Yorkshire terrier"
]