development:
  adapter: mysql2
  encoding: unicode
  database: mimanada
  host: localhost
  pool: 5
  username: postgres
  password: password
test:
  adapter: mysql2
  encoding: unicode
  database: mimanada_test
  host: localhost
  pool: 5
  username: postgres
  password: password

production:
  adapter: mysql2
  encoding: unicode
  database: mimanada_prod
  host: localhost
  pool: 5
  username: ENV['MIMANADA_DB_USER']
  password: ENV['MIMANADA_DB_PWD']