development:
  adapter: postgresql
  encoding: unicode
  database: mimanada
  host: localhost
  pool: 5
  username: postgres
  password: password
test:
  adapter: postgresql
  encoding: unicode
  database: mimanada_test
  host: localhost
  pool: 5
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: mimanada_dev
  host: localhost
  pool: 5
  username: postgres
  password: password