development:
  adapter: mysql2
  database: mimanada
  host: localhost
  pool: 5
  username: root
  password: root
test:
  adapter: mysql2
  database: mimanada_test
  host: localhost
  pool: 5
  username: root
  password: root

production:
  adapter: mysql2
  database: mimanada_prod
  host: localhost
  pool: 5
  username: <%= ENV['MIMANADA_DB_USER'] %>
  password: <%= ENV['MIMANADA_DB_PWD'] %>
