# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4022e062a83a6613fa09c3e34ec58d2c211bc2e9599f0c4ccee7744b05bf4fa7a53523d98940721262573114f908773f492e5a5b387b002d26f887a8c848d491

test:
  secret_key_base: 38316504dab60c447e7386ca0fd739ab035963ad6a058ef9a5eb814f16f55a4c5cb9b24d4967aadd65f79aedcfc7eb34db5b294db287cc55b6338245bea87d63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_KEY_BASE"] %
